<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.company</groupId>
        <artifactId>automation-root</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <properties>
        <cucumber.tags></cucumber.tags>
    </properties>

    <artifactId>backend-tests</artifactId>
    <packaging>jar</packaging>


    <dependencies>
        <!-- Cucumber + TestNG + Spring -->

            <!-- Cucumber Java -->
            <dependency>
                <groupId>io.cucumber</groupId>
                <artifactId>cucumber-java</artifactId>
                <version>7.14.0</version>
                <scope>test</scope>
            </dependency>

            <!-- Cucumber TestNG -->
            <dependency>
                <groupId>io.cucumber</groupId>
                <artifactId>cucumber-testng</artifactId>
                <version>7.14.0</version>
                <scope>test</scope>
            </dependency>

            <!-- TestNG -->
            <dependency>
                <groupId>org.testng</groupId>
                <artifactId>testng</artifactId>
                <version>7.8.0</version>
                <scope>test</scope>
            </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <systemPropertyVariables>
                        <cucumber.filter.tags>${cucumber.tags}</cucumber.filter.tags>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
