<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.company</groupId>
        <artifactId>automation-root</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <properties>
        <cucumber.tags></cucumber.tags>
    </properties>
    <artifactId>frontend-tests</artifactId>
    <packaging>jar</packaging>

    <build>
        <plugins>

            <plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <version>1.15.0</version>

    <executions>

        <!-- Install BOTH Node and npm -->
        <execution>
            <id>install-node-npm</id>
            <goals>
                <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
                <nodeVersion>v18.19.0</nodeVersion>
                <npmVersion>9.8.1</npmVersion>
            </configuration>
        </execution>

        <!-- npm install -->
        <execution>
            <id>npm-install</id>
            <goals>
                <goal>npm</goal>
            </goals>
            <configuration>
                <arguments>install</arguments>
            </configuration>
        </execution>

        <!-- run Playwright -->
        <execution>
            <id>playwright-test</id>
            <phase>test</phase>
            <goals>
                <goal>npm</goal>
            </goals>
            <configuration>
                <arguments>run test</arguments>
                <environmentVariables>
                    <TAGS>${cucumber.tags}</TAGS>
                </environmentVariables>
            </configuration>
        </execution>

    </executions>
</plugin>


        </plugins>
    </build>


</project>
